package com.example.rideready.navigation

const val ROUT_HOME= "home"
const val ROUT_SPLASH= "splash"
const val ROUT_SIGNUP= "signup"
const val ROUT_LOGIN= "login"
const val ROUT_CHECKOUT= "checkout"
const val ROUT_CAR= "car"
const val ROUT_ABOUT= "about"
const val ROUT_BUGATTI= "bugatti"
const val ROUT_BMW= "bmw"
const val ROUT_MERCEDES= "car"
const val ROUT_ROLLSROYCE= "car"
const val ADD_CAR_URL = "add_car"
const val VIEW_CAR_URL = "view_car"
const val VIEW_CARS_URL = "view_cars"
const val ADD_ACCOUNT = "add_account"
const val VIEW_ACCOUNT = "account"